// 40 extra questions: [question, CORRECT answer, wrong, wrong, wrong] - together with quiz.js this gives a 100-question bank.
module.exports = [
  ["What is an \"endpoint\" in a web API?", "A URL where a service receives requests", "The last line of a program", "A type of monitor", "A password rule"],
  ["What does \"HTML\" stand for?", "HyperText Markup Language", "High Transfer Machine Language", "Hyperlink Text Mode Logic", "Home Tool Markup Language"],
  ["Which language is used to style web pages?", "CSS", "SQL", "Bash", "Assembly"],
  ["What is \"inference\" in machine learning?", "Using a trained model to make predictions", "Collecting training data", "Deleting old models", "Labelling images"],
  ["What is a \"neural network\" layer?", "A group of connected units that transforms its inputs", "A layer of paint on a chip", "A stack of web pages", "A network cable bundle"],
  ["What is \"training data\"?", "Examples a model learns from", "Only the final answers", "A list of passwords", "The model's error log"],
  ["What does \"role prompting\" mean?", "Asking the model to act as a specific expert or persona", "Assigning user roles in a database", "Ranking prompts by length", "Sorting prompts alphabetically"],
  ["Why specify an output format in a prompt?", "It makes the response predictable and easier to use", "It makes the model faster", "It removes the need for training", "It hides the prompt"],
  ["What is an \"embedding\" in AI?", "A numeric vector that represents the meaning of text or images", "A video inside a web page", "A hardware cable", "A type of password hash"],
  ["What is a vector database used for?", "Searching items by similarity of their embeddings", "Drawing vector graphics", "Storing only spreadsheets", "Compiling code"],
  ["What does \"grounding\" an AI answer mean?", "Basing it on trusted, provided sources", "Turning the computer off", "Making it shorter", "Translating it"],
  ["What does \"multimodal\" mean for an AI model?", "It handles more than one type of input, like text and images", "It runs on many computers", "It speaks only one language", "It has multiple passwords"],
  ["What does the \"max tokens\" setting limit?", "The length of the generated output", "The number of users", "The screen resolution", "The training time"],
  ["What is a \"hyperparameter\"?", "A setting chosen before training, like the learning rate", "A very large parameter", "A hardware part", "A type of dataset"],
  ["What is a \"loss function\"?", "A measure of how wrong the model's predictions are", "A function that deletes data", "A network firewall rule", "A way to lose weights"],
  ["What is \"gradient descent\"?", "An optimisation method that adjusts weights to reduce loss", "A hiking technique", "A data compression format", "A type of database query"],
  ["What is \"unsupervised learning\"?", "Finding patterns in unlabelled data", "Learning with a teacher labelling everything", "Learning only from rewards", "Copying another model exactly"],
  ["What is a chatbot?", "A program that converses with users in natural language", "A type of keyboard", "A video codec", "A search index"],
  ["What is \"transfer learning\"?", "Reusing a model trained on one task as a starting point for another", "Copying files between computers", "Moving a model to the cloud", "Transferring user accounts"],
  ["What is \"model distillation\"?", "Training a smaller model to imitate a larger one", "Boiling data down to one row", "Removing all parameters", "Merging two databases"],
  ["What is \"quantization\" in AI?", "Reducing numeric precision to make models smaller and faster", "Counting how many users there are", "Adding more layers", "Increasing the temperature"],
  ["What is an \"AI agent\"?", "A system that uses a model to plan and take actions toward a goal", "A human customer support worker", "A hardware chip", "A type of spreadsheet"],
  ["What is \"function calling\" (tool use) in an LLM?", "The model requests that external functions or APIs be run", "The model deletes its own code", "The user calls the model by phone", "A way to shorten prompts"],
  ["What does \"responsive design\" mean?", "A layout that adapts to different screen sizes", "A site that replies to emails", "A very fast server", "A site with many images"],
  ["Which CSS feature applies styles for specific screen widths?", "Media queries", "Pseudo-classes only", "Keyframes", "Variables"],
  ["What does \"DOM\" stand for in web development?", "Document Object Model", "Data Output Method", "Digital Order Map", "Display Order Manager"],
  ["Which HTML element is meant for the main navigation links?", "<nav>", "<marquee>", "<blink>", "<font>"],
  ["What does ARIA provide on a web page?", "Attributes that make content accessible to assistive technology", "Faster image loading", "Extra colour themes", "Database access"],
  ["What is the purpose of alt text on an image?", "Describing the image for screen readers and when it fails to load", "Making the image larger", "Adding a border", "Speeding up the server"],
  ["What does localStorage do?", "Keeps data in the browser even after the page is closed", "Stores data on the web server", "Deletes cookies", "Encrypts the page"],
  ["What is JSON?", "A lightweight text format for structured data", "A JavaScript compiler", "A CSS framework", "An image format"],
  ["What is CSS Flexbox mainly used for?", "One-dimensional layout and alignment of items", "Playing videos", "Storing data", "Encrypting forms"],
  ["Which is good practice for a clear AI prompt?", "State the goal, audience, constraints and format", "Use as few words as possible", "Avoid giving any context", "Repeat the same word many times"],
  ["What is \"iterative prompting\"?", "Refining the prompt over several attempts using the results", "Sending the same prompt forever", "Using only one-word prompts", "Deleting the model between attempts"],
  ["What does \"negative prompting\" mean?", "Telling the model what to avoid", "Writing a rude prompt", "Asking the model to be sad", "Using negative numbers"],
  ["What is \"model drift\"?", "Performance getting worse as real-world data changes", "A model moving between servers", "A model forgetting its name", "A faster training method"],
  ["What is \"explainable AI\"?", "Methods that help people understand why a model made a decision", "AI that writes manuals", "AI that explains jokes", "A slow model"],
  ["What is a benchmark for AI models?", "A standard test used to compare model performance", "A type of GPU", "A chat window", "A training dataset label"],
  ["What is \"synthetic data\"?", "Artificially generated data used for training or testing", "Data stolen from users", "Data stored on paper", "Encrypted backups"],
  ["What is \"latency\" for an AI service?", "The delay between sending a request and getting a response", "The model size", "The number of parameters", "The price per token"],
];
